#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'
fi

#
# Editors
#

export EDITOR='emacs -Q'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_GB.UTF-8'
fi

# Disable spring, always
export DISABLE_SPRING=1

# If bullet is installed, show the footer
export BULLET_FOOTER=true

export AWS_VAULT_KEYCHAIN_NAME=login

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

# add mysql 5.6 tools to the path
if [[ -d "/usr/local/opt/mysql@5.6/bin" ]]; then
  path=(
    "/usr/local/opt/mysql@5.6/bin"
    $path
  )
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Chruby
if [[ -d "/usr/local/share/chruby" ]]; then
  source /usr/local/share/chruby/chruby.sh
  source /usr/local/share/chruby/auto.sh
fi

# yarn
export YARN_CONFIG="$HOME/.config/yarn"
if [[ -d "$YARN_CONFIG" ]]; then
  path=(
    `yarn global bin`
    $path
  )
fi

# nodenv
if [[ -d "$HOME/.nodenv" ]]; then
  eval "$(nodenv init -)"
fi

# nvm
if [[ -d "$HOME/.nvm" ]]; then
  export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"
  [ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"
fi

# direnv
if [[ -x "/usr/local/bin/direnv" ]]; then
  eval "$(direnv hook zsh)"
fi

# scm puff
if [[ -x "/usr/local/bin/scmpuff" ]]; then
  eval "$(scmpuff init -s)"
fi
