#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# don't expand filenames from symbols (useful for passing args to rake tasks)
unsetopt nomatch

alias b="bundle exec"
alias e="emacsclient -c"
alias ed="emacs --daemon"
alias ek="emacsclient -e '(kill-emacs)'"
alias replace="ruby -ni.bak -e \"gsub!(ARGV[1], ARGV[0])\""
