#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# don't expand filenames from symbols (useful for passing args to rake tasks)
unsetopt nomatch

alias be='bundle exec'
alias gs='git status'
alias ga='git add .'
alias gr='git reset HEAD .'
alias gco='git checkout -- .'

function replace() {
  perl -0 -i -p -e "s/${1}/${2}/gms" $@[3,-1]
}

function branch_cleanup() {
  git branch --merged master | grep -v "\* master" | xargs -n 1 git branch -d
}
